version: '2'
services:
  web:
    build: ./proyecto
    container_name: Bphp_apache_test
    working_dir: /var/www/html/Proyecto1/
    entrypoint: php artisan serve --port=8080 --host 0.0.0.0
    tty: true 
    depends_on:
        - db
        - pgdb
    volumes:
        - ./proyecto:/var/www/html/
        - ./confphp/ini:/usr/local/etc/php/conf.d
    ports:
        - 8000:80
        - 8080:8080
        - 8180:8180
  db:
    image: mysql
    container_name: Bmysqldb_test
    command: --default-authentication-plugin=mysql_native_password
    environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: dbPilar
          MYSQL_USER: user
          MYSQL_PASSWORD: user
    ports:
          - 8085:3306
  pgdb:
    image: postgres
    container_name: Bmypg_test
    environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: pilardb
    ports:
         - 8082:5432
  adminer:
    container_name: Adminer_test
    image: adminer
    ports:
      - 8090:8080
